const ASSET_BASE='https://raw.githubusercontent.com/Oflakstudio/Priyanka-vishwakarma-portfolio/main/assets';
const PROJECTS={
  azure:{index:'01',kicker:'Collection / Azure Heirloom',title:'Azure Heirloom',description:'A womenswear collection inspired by spirituality, architecture, traditional weaving, and the visual heritage of Banaras.',details:['Palette: blue, ivory, gold, and related tones.','Research translated through woven references, embroidery, decorative borders, and embellished details.','Full-look documentation includes front, side, and back views with close-up finishing references.'],images:['the-azure-hairloom-01.jpg','the-azure-hairloom-02.jpg','the-azure-hairloom-03.jpg','the-azure-hairloom-04.jpg','the-azure-hairloom-05.jpg','the-azure-hairloom-06.jpg','the-azure-hairloom-07.jpg']},
  womenswear:{index:'02',kicker:'Design series / Womenswear',title:'Womenswear Design Series',description:'Seven womenswear design concepts spanning contemporary, occasion, evening, and fusion-inspired silhouettes.',details:['Design vocabulary includes draping, layered silhouettes, cut-outs, gathered details, statement sleeves, fitted forms, and flowing garments.','Supporting boards cover fabric details, colour palettes, construction references, and inspiration.','Presented through front, side, and back-view fashion development.'],images:['aurelia.jpg','rayaa.jpg','modern-duality.jpg','refiend-contrast.jpg','the-amaranthine-form.jpg','rangrezz-01.jpg','the-royal-blue-garden.jpg','rangrezz-02.jpg','rangrezz-03.jpg','rangrezz-04.jpg','rangrezz-05.jpg']},
  textile:{index:'03',kicker:'Textile / Surface development',title:'Textile & Surface Development',description:'A focused exploration of tie-and-dye and supporting textile research, connecting surface decisions with outfit direction.',details:['Four tie-and-dye directions: diagonal stripe, shibori horizontal pattern, curved line, and diamond shibori pattern.','Documented pattern, texture, and visual effects alongside proposed outfit applications.','Supporting research includes fabric swatches, manipulation studies, and colour-story development.'],images:['textile-surface.jpg','fabric.jpg','manipulations.jpg','colour-story.jpg']}
};
const nav=document.getElementById('nav');
window.addEventListener('scroll',()=>nav.classList.toggle('scrolled',window.scrollY>56),{passive:true});
const menu=document.getElementById('mobileMenu');
const toggle=document.getElementById('menuToggle');
toggle.addEventListener('click',()=>{toggle.classList.toggle('open');menu.style.display=toggle.classList.contains('open')?'flex':'none';document.body.style.overflow=toggle.classList.contains('open')?'hidden':''});
document.querySelectorAll('[data-scroll]').forEach(el=>el.addEventListener('click',()=>{const id=el.dataset.scroll;document.getElementById(id)?.scrollIntoView({behavior:'smooth'});toggle.classList.remove('open');menu.style.display='none';document.body.style.overflow=''}));
const modal=document.getElementById('modal'), modalClose=document.getElementById('modalClose');
const modalKicker=document.getElementById('modalKicker'), modalIndex=document.getElementById('modalIndex'), modalTitle=document.getElementById('modalTitle'), modalDescription=document.getElementById('modalDescription'), modalDetails=document.getElementById('modalDetails'), modalGallery=document.getElementById('modalGallery');
function openProject(key){const p=PROJECTS[key];if(!p)return;modalKicker.textContent=p.kicker;modalIndex.textContent=p.index;modalTitle.textContent=p.title;modalDescription.textContent=p.description;modalDetails.innerHTML=p.details.map(t=>`<p>${t}</p>`).join('');modalGallery.innerHTML=p.images.map((file,i)=>`<img class="${i===0?'full':''}" src="${ASSET_BASE}/images/${file}" alt="${p.title} — board ${i+1}" loading="lazy">`).join('');modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeProject(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelectorAll('[data-project]').forEach(el=>el.addEventListener('click',()=>openProject(el.dataset.project)));
modalClose.addEventListener('click',closeProject);document.querySelector('[data-close]').addEventListener('click',closeProject);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProject()});
document.getElementById('contactForm').addEventListener('submit',e=>{e.preventDefault();document.getElementById('formSuccess').classList.add('show');e.target.reset()});
